---
abstract: 'Collate text files into a book-ish sort of thing.'
author:
  - 'Leam Hall <leamhall@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: bookbot
provides:
  Book:
    file: lib/Book.pm
    version: '0.03'
  Section:
    file: lib/Section.pm
    version: '0.03'
  bookbot:
    file: lib/bookbot.pm
    version: '0.01'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
